name = "harumcare-backend"
main = "dist/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "harumcare-backend"

[env.production.vars]
NODE_ENV = "production"
